name: CI

on:
  push:
    branches:
    - develop
    - master
    tags:
      - "v*.*.*"

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - run: yarn install
    - run: xvfb-run -a yarn run test
      if: runner.os == 'Linux'
    - run: yarn run test
      if: runner.os != 'Linux'
    - name: Publish
      if: matrix.os == 'ubuntu-latest'
      run: yarn run package
    - name: Release
      uses: softprops/action-gh-release@v0.1.13
      if: startsWith(github.ref, 'refs/tags/') && matrix.os == 'ubuntu-latest'
      with:
        files: '*.vsix'
        fail_on_unmatched_files: true
